import { addCommand } from '../lib/plugins.js';
import { log } from '../src/utils/logger.js';
import { UI } from '../src/utils/design.js';
import { validateText } from '../src/utils/validator.js';
import { withTimeout } from '../src/utils/timeout.js';
import { checkRateLimit } from '../lib/ratelimit.js';

addCommand({
    pattern: 'imagine',
    alias: ['dalle', 'img', 'aiimage'],
    category: 'ai',
    handler: async (m, { conn, text }) => {
        try {
            // Rate limiting: 10 requests per minute
            const rateLimit = await checkRateLimit(m.sender, 'imagine', 10, 60);
            if (!rateLimit.allowed) {
                return m.reply(UI.error('Rate Limit', `Too many image requests. Wait ${rateLimit.resetIn}s`, `Limit: ${10} images per minute\nTry again in ${rateLimit.resetIn} seconds`));
            }

            // Input validation
            const prompt = validateText(text, true);

            await conn.sendMessage(m.chat, { react: { text: '🎨', key: m.key } });

            // Generate image URL
            const imageUrl = `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}`;

            // Send with timeout protection
            await withTimeout(
                conn.sendMessage(m.chat, {
                    image: { url: imageUrl },
                    caption: `🔮 *Mantra Vision*\n${global.divider}\n📝 *Prompt:* ${prompt}\n\n_Generated by Pollinations AI_`
                }, { quoted: m }),
                30000,
                'AI image generation'
            );

            await conn.sendMessage(m.chat, { react: { text: '✅', key: m.key } });

            log.action('AI image generated', 'ai', { prompt: prompt.substring(0, 50), user: m.sender });

        } catch (error) {
            log.error('AI image generation failed', error, { command: 'imagine', prompt: text?.substring(0, 50), user: m.sender });

            await conn.sendMessage(m.chat, { react: { text: '❌', key: m.key } });

            if (error.message.includes('validation')) {
                return m.reply(UI.error('Invalid Prompt', error.message, 'Provide a description\\nExample: .imagine beautiful sunset\\nExample: .imagine cyberpunk city'));
            }

            if (error.message.includes('timed out')) {
                return m.reply(UI.error('Timeout', 'Image generation took too long', 'Try simpler prompt\\nCheck internet connection\\nTry again later'));
            }

            m.reply(UI.error(
                'Image Generation Failed',
                error.message || 'Failed to generate image',
                'Try a different prompt\\nCheck your internet connection\\nAPI might be temporarily unavailable'
            ));
        }
    }
});